title: Joey Beninghove
description: Full stack web developer specializing in Rails and Javascript.
url: https://joey.io
permalink: /:title/
excerpt_separator: <!--more-->
author:
  name: Joey Beninghove
  twitter: joeybeninghove

twitter:
  username: joeybeninghove

logo: /assets/joey.jpg

social:
  name: Joey Beninghove
  links:
    - https://twitter.com/joeybeninghove
    - https://facebook.com/joeybeninghove
    - https://github.com/joeybeninghove
    - https://www.linkedin.com/in/joeybeninghove

include:
  - _redirects
exclude:
  - /src
  - /Gemfile
  - /Gemfile.lock
  - /package.json
  - /yarn.lock
  - /node_modules
  - /tailwind.js
  - /webpack.config.js
  - /postcss.config.js
  - /README.md
